### ISSUE TITLE
Mobile Browser Keyboard Issue

### ISSUE THREAD

**Issue by microbmen** [ct6502/apple2ts#21]
**Describe the bug**
I've tested on iOS and Android Mobile browsers.

iOS - keyboard functions as intended
Android - Tried Chrome browser and Samsung browser, as well as a few different keyboards.  Key entry doesn't work in Android. 

**To Reproduce**
Go to apple2ts.com on Android.  Try keyboard.

**Expected behavior**
When I tap on the emulated display the keyboard comes up.  However when entering keystrokes, in either lowercase or uppercase do not function.  Interesting enough it appears the enter "return" works. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Fold
 - OS: Android - Android 13
 - Browser - Tried a few (Samsung browser, and Chrome)

**Additional context**
N/A

**Comment by ct6502** [comment]
Thanks for reporting this! We'll take a look.

**Comment by microbmen** [comment]
Any word on this bug?  

If you could get this fixed you would have the only active Android supported A2 emulator currently available.  Fully functional with sound, .hdv support, and it works really well with a bluetooth attached joystick.   Further no APK install is needed.  
Fixing keyboard support would be huge here...

Thanks Chris.

```
**Details about other Android Apple II EMUs:**

KEGS is off the play store, works if you side load, however bt joystick makes host OS calls and isn't working in the EMU
Apple2ix works if you side load, however doesn't support hdv
Candy Apple works if you side load, however doesn't support a whole bunch of stuff and sound on Android 12 is buggy.

```

**Comment by ct6502** [comment]
Okay, that was a big pain because Android really doesn't want to send hardware keyboard events. Lots of details here:
https://bugs.chromium.org/p/chromium/issues/detail?id=118639
https://stackoverflow.com/questions/36753548/keycode-on-android-is-always-229

I also fixed the canvas scaling, since Android wanted to use "outerWidth/Height" rather than "innerWidth/Height".

**Comment by ct6502** [comment]
@microbmen if you get a chance, try out the keyboard on Android. I had to hardcode the special keys like Enter and Backspace, so let me know if I'm missing any others.

**Comment by microbmen** [comment]
Looks good.  a few keys like ESC and the Arrow directionals don't work (i have a soft keyboard that gives those), but its fine as you provide those keys on the UI.  
A strange bug happens on occasion where you can type a single character and it freezes.  If I turn off the UI Caps Lock, it goes back to working fine.  In other words, if I use the keyboard Caps Lock vs. UI Caps Lock it works fine, otherwise on occasion it only allows a single character entry.  I couldn't figure out how to trigger this bug.  Not a big deal.

Also the Canvas scaling is much better! great job.

**Comment by ct6502** [comment]
@microbmen glad to hear the keys work better. Just curious, what soft keyboard are you using? I could try to add it to the Android simulator and see if I can get more keys working. It's probably just a matter of translating the onInput key name to the expected key code name.
If you come up with a reproduce case for the Caps lock bug, please log it as a new issue. Thanks!

**Comment by microbmen** [comment]
Yea, I tried a few. Gboard, and Swiftkey are my most used.  

However - for people like us -  'Hacker's Keyboard'  is the only keyboard with directionals, ESC, CTRL, etc. keys.  Its very useful for things like Vi, terminal connections, etc.

https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&pli=1
