### ISSUE TITLE
Windows: 'VITE_GIT_SHA' is not recognized

### ISSUE THREAD

**Issue by flaith-nycd** [ct6502/apple2ts#30]
**Trying to start the emulator under Windows 11**
After a fresh clone and `npm install,` `npm start` doesn't work.

**Here is the behavior**
D:\PROJECTS\APPLE\CHRIS-TORRENCE\apple2ts(main -> origin)
$ `npm install`

added 529 packages, and audited 530 packages in 14s

77 packages are looking for funding
  run npm fund for details

found 0 vulnerabilities

D:\PROJECTS\APPLE\CHRIS-TORRENCE\apple2ts(main -> origin)
$ `npm start`

> apple2ts@1.1.0 start
> VITE_GIT_SHA=`git rev-parse --short HEAD` vite --open

'VITE_GIT_SHA' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

Maybe I'm missing something :)

Thanks for your help

**Comment by ct6502** [comment]
This isn't surprising. That "vite_git_sha" seems like a fragile feature. It's used to put the most recent GIT hash number at the bottom of the emulator. Maybe I'll just get rid of it...

**Comment by ct6502** [comment]
Fixed in 1bd7312d4cdb37f44af79cba1e1fc11600542ba6
