### ISSUE TITLE
Add a "View Memory" panel

### ISSUE THREAD

**Issue by ct6502** [ct6502/apple2ts#34]
Is this even necessary or useful? Can the user edit memory as well?

**Comment by kktos** [comment]
> Is this even necessary or useful?
necessary, no. useful, very much.
> Can the user edit memory as well?
yes ;)

**Comment by ct6502** [comment]
May need to convert part of the debug view into a "tabbed" pane, so there's enough room.

**Comment by kktos** [comment]
As you already have a live view, you can say that the MemoryViewer would work with the machine paused.
Therefore, we may open an new window/tab and have a full page for the MemoryViewer.
Now, how can these 2 will be able to communicate ?
The Broadcast API may be of help, here.
[Broadcast_Channel_API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API)

**Comment by kktos** [comment]
Found a nice little tutorial : [Web API, Broadcast Channel in React with a Custom Hook](https://www.youtube.com/watch?v=VNd3r6I00Ck)
