### ISSUE TITLE
65C02 BIT emulation bug

### ISSUE THREAD

**Issue by mgolombeck** [ct6502/apple2ts#40]
**Apple Core Detects bugs in BIT opcode flag operations**
It seems like the flags of the 65C02 BIT opcodes are not set correctly.

![Bildschirmfoto 2024-01-19 um 10 56 42](https://github.com/ct6502/apple2ts/assets/26803128/02d3475d-4203-4dfe-940a-2cad73aab2bf)

**To Reproduce**
The following screenshot shows the code that fails of the BIT immediate opcode: 

<img width="1527" alt="Bildschirmfoto 2024-01-19 um 11 07 47" src="https://github.com/ct6502/apple2ts/assets/26803128/c4b6d74d-58a7-467b-8d7e-7e249f7ce8b2">

**Further Remarks**
Flag operations of other BIT addressing modes also fail.

**Comment by ct6502** [comment]
I didn't realize that the BIT in Immediate mode only set the Z flag, not N or V! Should be an easy fix. Thanks for logging it.
