### ISSUE TITLE
The Apple II Game "Drol" Controls Not Working Right

### ISSUE THREAD

**Issue by RabbitRetro** [ct6502/apple2ts#41]
**Bug Description**
In the Apple II game, "Drol", the controls are sluggish. The character cannot reliably move up and down (and sometimes moving left and right or firing doesn't happen at all).

**To Reproduce**
First, watch this video: [Apple II Drol Game Footage] (https://www.youtube.com/watch?v=Ved7ZoKhIf0)
1) Launch game after locating .dsk or .do image file from this URL:
[Drol Disk Archive] (https://archive.org/details/a2_asimov_drol)
2) Press a key to start game once it has loaded.
3) use controls... up, down, right, left arrow... space-bar to fire.

**Expected behavior**
As seen in the video, the main character should respond to the controls smoothly without pauses.

**Screenshots**
See video link above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox

**Additional context**
Note that this problem happens with all Apple II emulators I have tested it with (KEGS and applewin), so it isn't a bug specific to the apple2ts emulator. The game always runs fine on real Apple II hardware.

It is likely this Br0derbund game program has some very specific timing for displaying animation and monitoring the keyboard controls.

**Comment by nick3092** [comment]
I don't believe this is a bug in anything, you have the wrong keys listed.  you should not use the up and down arrow keys (Apples prior to the IIe did not have up and down arrows).  Instead you should use A and Z.  The game actually interprets the down arrow as Ctrl-J and put the game in joystick mode.  I suggest repeating your test case and never touching the down arrow.

Drol manual outlining the proper navigation keys and usage of Ctrl-J/Ctrl-K

http://www.textfiles.com/apple/DOCUMENTATION/drol

**Comment by ct6502** [comment]
I actually just fixed this with 2b51e3a. It turns out that up/down was only controlled by A and Z - the up/down arrow keys don't seem to work in Drol. However, my emulator now overrides that so you can use either A/Z or all of the arrow keys. I also added support for a gamepad controller. So everything should now be working :-)
