### ISSUE TITLE
In monochrome, pixel scaling results in ugly artifacts

### ISSUE THREAD

**Issue by inexorabletash** [ct6502/apple2ts#42]
**Describe the bug**
In monochrome, pixel scaling results in ugly artifacts. Note that this affects only the visual display in the browser; the actual rendering (which can be accessed by using the 'Copy Screen' shortcut) is flawless.

All examples in macOS 14.2.1 with a retina (high-DPI) display.

When I open in Chrome 120 the default sizing on my monitor results in horizontal and vertical scaling artifacts - note the desktop background which should be a perfect checkerboard, and horizontal lines in the title bar which are inconsistently spaced:

<img width="592" alt="image" src="https://github.com/ct6502/apple2ts/assets/771547/de3779a6-e7a1-4921-bd3c-85a1e79c28c2">

If I try to adjust the window size to eliminate horizontal artifacts, I still can't get rid of vertical artifacts:
![image](https://github.com/ct6502/apple2ts/assets/771547/28b83ad4-edea-4535-a353-a2a8a3be815c)

In Firefox (109) if you shrink the window enough it stops trying to nearest-neighbor scale and does filtering, which eliminates the artifacts but now everything is blurry - I think that's actually better!

<img width="470" alt="image" src="https://github.com/ct6502/apple2ts/assets/771547/72498ae3-76f1-44c7-97a5-6a4601972021">

In Safari 17.2.1 the effect is similar when scaling to eliminate horizontal artifacts:
<img width="568" alt="image" src="https://github.com/ct6502/apple2ts/assets/771547/8e7cb96d-2f96-4902-9a6d-00f5b53d54d6">

When shrunk down it's just ugly nearest neighbor sampling:

<img width="466" alt="image" src="https://github.com/ct6502/apple2ts/assets/771547/17197f4c-9adc-4fe3-b693-dcc788138f70">

**To Reproduce**
1. Grab an A2D build from https://github.com/a2stuff/a2d/releases [e.g. 1.4-alpha4 English](https://github.com/a2stuff/a2d/releases/download/v1.4-alpha4/A2DeskTop-1.4-alpha4-en.zip), and unzip the files.
2. At https://apple2ts.com/ click the S7D1 drive icon, and select the HDV file from the previous step.
3. Click the Boot button
4. Click the screen type button twice to select Green
5. In the emulated desktop, double-click A2.Desktop to open a window
6. Try to resize the window to eliminate both vertical and horizontal pixel doubling.

**Expected behavior**
There's an easy to achieve window size where pixels aren't doubled.

Here's apple2js, although note that it does not scale the image, so it's having an easier time:
<img width="578" alt="image" src="https://github.com/ct6502/apple2ts/assets/771547/0775a467-ce52-45a8-96c4-85189f3687b9">

Here's Virtual ][ which looks like it's doing filtered scaling at all sizes, which looks pretty good on a retina display:

<img width="540" alt="image" src="https://github.com/ct6502/apple2ts/assets/771547/7a7e9cdb-5d5b-4a6d-92c0-d7fe99e0110f">

![image](https://github.com/ct6502/apple2ts/assets/771547/e45c4946-084a-4e8b-b66f-b169977db50b)

<img width="957" alt="image" src="https://github.com/ct6502/apple2ts/assets/771547/993c92a0-9226-4a17-85e4-1244fcc6392b">

**Additional context**

Thoughts to try:
* Ensure that there's not an off-by-one when rendering the display 560x384 bitmap to the final canvas, and that the CSS scaling the display canvas is behaving as expected.
* On high-DPI display (`window.devicePixelRatio >= 2`) use bilinear filtering not nearest neighbor sampling when rendering, and ensure that the display canvas is scaled by the device pixel ratio (e.g. if DPR is 2 you want a final canvas that's twice the desired height/width, and then CSS scaled). It's a pain but doable.

**Comment by ct6502** [comment]
Just a heads up - this seems a lot better once I switched to using image scaling. But please give it a try and let me know if you see any more strange artifacts. Everything will be a tiny bit blurrier now that I'm using scaling, but hopefully it will look more like a CRT ;-)

Here's a big size:
![Screenshot 2024-01-27 at 9 05 32 PM](https://github.com/ct6502/apple2ts/assets/5461379/0ce11857-abd5-4f64-9deb-87cb568b3fad)

And here's a small size:
![Screenshot 2024-01-27 at 9 06 39 PM](https://github.com/ct6502/apple2ts/assets/5461379/54f819a8-9dce-46f5-95a5-3ad2ca5b91c5)

**Comment by inexorabletash** [comment]
Yes, scaling looks much better to me now. Thanks!

(I'm sure some users will prefer a different look, but that's par for the course with emulation!)
