### ISSUE TITLE
Migrate to Functional Components

### ISSUE THREAD

**Issue by kktos** [ct6502/apple2ts#44]
**Is your feature request related to a problem? Please describe.**
Not problem. At least, yet. The code is mainly structured using Class Components which are now deprecated with React.

**Describe the solution you'd like**
Slowly migrating to Function Components : [See how to migrate.](https://react.dev/reference/react/Component#alternatives)

**Describe alternatives you've considered**
None

**Additional context**
ok, I'm no React dev (Angular&Vue) but I'd be glad to help if I can.

**Comment by ct6502** [comment]
In general I agree with this feature request. There was some reason that I tended to use class components, but I can't remember the details, so I would want to remember why and make sure we don't go down the wrong path. Luckily this can be done slowly, as you noted.

**Comment by ct6502** [comment]
Partially addressed in dd27cdc

**Comment by kktos** [comment]
Nice one. but you can use the Object destructuring for the props.
So, for instance, instead of
```typescript
const DiskDrive = (props: { drive: number, setShowFileOpenDialog: (show: boolean, drive: number) => void }) => {
    const dprops = handleGetDriveProps(props.drive);
    let img1: string;
    [ ... ]
```
you may have
```typescript
type DiskDriveProps = {
    drive: number,
    setShowFileOpenDialog: (show: boolean, drive: number) => void
};

const DiskDrive = ({ drive, setShowFileOpenDialog }) => {
    const dprops = handleGetDriveProps(drive);
    let img1: string;
    [ ... ]
```

it will make it easier to read, which is the key here ;)

**Comment by kktos** [comment]
Side note :
I see that in `handleGetDriveProps` you always return a string, even a possibly empty string.
That's ok but it would be easier if you have a not empty string or null.
So you may have somehting like:
```typescript
const DiskDrive = ({ drive, setShowFileOpenDialog }) => {
  const dprops = handleGetDriveProps(drive);
  let img1: string;
  if (dprops.hardDrive) {
    img1 = dprops.motorRunning ? imageList.hardDriveOn : imageList.hardDriveOff;
  } else {
    img1 = (dprops.filename) ?
      (dprops.motorRunning ? imageList.disk2on : imageList.disk2off) :
      (dprops.motorRunning ? imageList.disk2onEmpty : imageList.disk2offEmpty)
  }
  const filename = dprops.filename ?? "(empty)";
  let status = ['S7D1', 'S6D1', 'S6D2'][props.drive];
  status += dprops.status;
  return (
    <span className="driveClass">
      <img className="disk2"
        src={img1} alt={filename}
        title={filename}
        onClick={() => {
          if (dprops.filename) {
            if (dprops.diskHasChanges) {
              downloadDisk(dprops.diskData, filename);
            }
            resetDrive(props.drive);
          }
          setShowFileOpenDialog(true, props.drive);
        }} />
      <span className={"diskLabel"}>{dprops.filename}</span>
      <span className={"defaultFont diskStatus"}>{status}</span>
    </span>
  )
}

**Comment by kktos** [comment]
Ah, another thing:
Here, I suppose you have a disk icon and you want to handle the click.
But the DiskDrive component job is to display the proper icon and emit the click event. that's all.
The job of the parent component will be to do some appropriate action on this event.
Therefore, this is a onClick handler you wish to pass as a prop, not the setShowFileOpenDialog.
As a rule of thumb, we try not to bind too much the component inner gears. (cf [SOLID](https://en.wikipedia.org/wiki/SOLID))
;)

**Comment by ct6502** [comment]
Cool, thanks for these suggestions! Anything to make the code more proper and modern is appreciated.

To be honest, it was more of a struggle to convert to functional components that I expected, especially the Canvas and Display classes. I tried to use "useEffect" for doing initial updates, to do things the proper React way, but there were too many dependencies and I ended up using an evil "isInitialized" flag. I have a bad feeling that I'm doing way too many UI updates, but it was tricky to get the web worker (with the 6502) to properly update the GUI main thread.

I also tried using a global "context" to store a lot of the state properties, so I wouldn't have to pass them down so many layers. But for some reason I wasn't getting updates. I may try that route again now that the code is more stable.

**Comment by ct6502** [comment]
@kktos I did refactor a few of the components to use object destructuring for the props. I left the event handling code in DiskDrive alone. I think it's better to leave that as a self-contained component. Moving the onClick handler code up a level might be better from a pure OO point of view, but then it mixes that component with the parent. Maybe I'll revisit in the future. Thanks!
