### ISSUE TITLE
King's Quest floppy disk does not boot properly

### ISSUE THREAD

**Issue by ct6502** [ct6502/apple2ts#51]
[King's Quest (woz-a-day collection).zip](https://github.com/ct6502/apple2ts/files/14213687/King.s.Quest.woz-a-day.collection.zip)

Uncompress zip, insert King's Quest disk A into floppy, then boot. Hangs at "Please wait..." screen. Debugger shows that it's oscillating between PC=0xFFFF and 0x0.

![Screenshot 2024-02-08 at 12 19 24 PM](https://github.com/ct6502/apple2ts/assets/5461379/439f9e91-7ba4-48ff-8c7a-1b0d8362bf0d)

Debugging shows that it might be messing up in the following block:
![Screenshot 2024-02-08 at 12 28 07 PM](https://github.com/ct6502/apple2ts/assets/5461379/0e3d4b12-7552-422e-b3ee-8604061e483b)

Perhaps the LDA $C08C,X is doing something wrong with the memory softswitches?

**Comment by ct6502** [comment]
If I put a breakpoint at FF26, the accumulator contains $C0, which was presumably just read from the woz disk image. If I change the accumulator to $C9, then the game boots properly. This might be some sort of copy protection which my emulator fails to emulate. Virtual II has no problem booting the game.

![Screenshot 2024-03-24 at 9 35 14 PM](https://github.com/ct6502/apple2ts/assets/5461379/49adf9e1-5a73-4ae2-9d15-e1333324ecb1)

**Comment by ct6502** [comment]
Space Quest has the exact same issue - break at $FF26, change the accumulator to $C9, then continue.
https://archive.org/download/wozaday_Space_Quest

**Comment by univta0001** [comment]
The recent fixes in WOZ handling, somehow allow the King Quest and Space Quest to boot and reach the main screen

**Comment by ct6502** [comment]
Fixed as part of fixes for #81

**Comment by ct6502** [comment]
Tested again on 4/19/2025 while working on fix for Stickybrear (#81), still works properly
