### ISSUE TITLE
can't paste text on windows chrome

### ISSUE THREAD

**Issue by tynbendad** [ct6502/apple2ts#54]
**Describe the bug**
just trying to paste some text into the basic prompt on windows 11 and chrome browser, neither ctrl-v or alt-v (as the instructions say) work - nothing happens.

**To Reproduce**
1. Go to apple2ts.com
2. Click on 'power on'
3. Click on 'reset'
4. Go to another window and copy some text
5. Go back to apple2ts window and try to paste it in with Alt-V or Ctrl-V
6. nothing happens (no text pasted)

**Expected behavior**
text should be pasted into the basic prompt

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11 latest normal
 - Browser: chrome latest normal

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by code-bythepound** [comment]
Thanks for reporting this.  Paste with ALT-V doesn't seem to work on Linux either.  A workaround is to use the 3 dot menu in the upper right, select "Find and edit" and then "Paste."  This works for me.
I'll look into whats going on.

**Comment by code-bythepound** [comment]
Closing issue.  Reopen if the fix doesn't work.
