### ISSUE TITLE
Hex bytes of a data table.

### ISSUE THREAD

**Issue by LelandLong** [ct6502/apple2ts#65]
Thanx for this repo & accompanying YouTube videos!
I'm trying to use your assembler to create the code in VSCode, create the .BIN file, and open it in your emulator.
Working great UNTIL .......
Pg 49 of your book (AL07-SAMPLE DATA PROGRAM) tries to introduce hex DATA using the 'HEX' opcode which your assembler throws an error on.
Is this a bug?
Certainly not a feature :)

**Comment by ct6502** [comment]
I changed this to a feature request. HEX isn't a real opcode. I'll think about adding support for it. But in the meantime, I would recommend using an actual assembler on the Apple II, like Merlin. Thanks for your support!
