### ISSUE TITLE
Assembler Opcode 'STA' Is not resulting in correct binary

### ISSUE THREAD

**Issue by LelandLong** [ct6502/apple2ts#66]
Your book, pg50 (AL07-SCREEN CLEAR PROGRAM 1A)
has the following code snippet:
PTR       EQU   $06
LOOP    STA   (PTR),Y

Which is supposed to assemble as:
LOOP    STA   (PTR),Y         030A-  91 06

Instead your assembler results in:
LOOP    STA   (PTR),Y         030A-  91

Final binary, which is missing the 06 (between 91 & C8):
 A9 04 85 07 A0 00 84 06 A9 A0 91 C8 D0 FB E6 07 A5 07 C9 08 90 F1 60

**Comment by ct6502** [comment]
I probably never added support for indirect addressing with labels. Switching to a feature request.
