### ISSUE TITLE
Accelerometer support

### ISSUE THREAD

**Issue by timriker** [ct6502/apple2ts#71]
It would be awesome on some games to map the accelerometer to joystick or arrow key or perhaps custom key inputs for mobile devices.

Currently in Total Replay entering ctrl-p on a mobile device without other input devices attached, does not move the cursor.

**Comment by ct6502** [comment]
Cool idea, I'll have to see what can be done. Just curious, what is the "ctrl-p" supposed to do?

**Comment by timriker** [comment]
ctrl-p on Total Replay starts an app to display joystick input. There are other apps that do the same thing. I mention this one as a known app you can get to. Pick Total Replay in your app, then at the menu screen hit ctrl-p.

**Comment by ct6502** [comment]
On a mobile device, you can actually use the little arrow key buttons to move the joystick left/right/up/down. It's not ideal, as it only moves from 0 to 128 to 255, nothing in between. But it's better than nothing. As an aside, you can also use the arrow keys on the desktop browser, and play Choplifter with nothing but the keyboard!

Right now it looks like there is an experimental Accelerometer API:
https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer

But it's not available on iOS, only Android. And currently, when you tilt the phone, the apple2ts switches from portrait to landscape mode. To support the accelerometer, we would need a way to disable the rotation. I'm going to close this issue for now. Feel free to reopen if/when the Accelerometer API supports both Android and iOS.
