### ISSUE TITLE
Unable to start Print Shop Companion

### ISSUE THREAD

**Issue by univta0001** [ct6502/apple2ts#79]
**Print Shop Companion hang at the menu page**
Apple2TS did not implement the WOZ weak bits properly rendering the hang in Print Shop Companion. The woz image can be obtained at https://archive.org/details/wozaday_The_Print_Shop_Companion

**To Reproduce**
1. Get the woz image from https://archive.org/details/wozaday_The_Print_Shop_Companion
2. Boot the disk in slot 6

**Expected behavior**
You should able to see all the options in Print Shop Companion

**Screenshots**
Screenshots of the hanging Print Shop Companion

![printshop](https://github.com/user-attachments/assets/e1b22ba6-90b4-4159-a2b6-983e4cb360ba)

**Comment by code-bythepound** [comment]
Change integrated and verified.
