### ISSUE TITLE
Mouse Support fails on state restore

### ISSUE THREAD

**Issue by jewettg** [ct6502/apple2ts#85]
**Describe the bug**
I have been playing "undead" and found that when I restore a state file, the mouse stops working.  The Apple //e (64k).
This happens after I have closed the windows, re-open the site, and restore the state.  The mouse worked before I closed the window, but after opening and restoring the state, the mouse no longer works.  A reboot with the disk image, the mouse works.

**To Reproduce**

1. Launch A2TS
2. Click folder icon (restore state)
3. Choose the state file.
4. Apple //e resumes, mockingboard and graphics all resume, but can not move the mouse on the screen.

**Expected behavior**
Expected all functionality to resume with all hardware functionality the same.

**Screenshots**
No real screenshots I can show.  Game is commercial, so I can not include it.  Including the state file would not do any good without the game disk image (32mb).

**Desktop (please complete the following information):**
 - OS: MacOS 15.1.1 (24B91)
 - Apple M2 Max, 32 GB, 
 - Firefox 133.0.3 (aarch64)

I am happy to work with you and debug anything.  Give me things to try.

**Comment by ct6502** [comment]
Thanks for reporting this! I've got a copy of Undead so I can try it out. I bet when you restore the state, the code isn't going through some sort of mouse setup routine that it normally goes through. Hopefully easy to fix.

**Comment by ct6502** [comment]
This should now be fixed. I save the mouse "mode" and the mouse X/Y clamping values in the peripheral I/O locations and then restore them afterwards. Both Mouse Paint and Undead seem to work fine when the state is restored. @jewettg if you have a chance, please test this and let me know if it fixes your issue. Note that you'll need to start a new Undead game, as those mouse values won't be in the saved state for your old game.

**Comment by jewettg** [comment]
CONFIRMED!  This is now fixed. 

Unfortunately, any previous "UNDEAD_32MB(5).a2ts” files that were created will not have the ability to restore with mouse support. 
 

Greg Jewett • Solutions Consultant / Developer • (512) 627-7290 • ***@***.***
LinkedIN: http://www.linkedin.com/in/redheadjewett
Don't print this e-mail unless it's necessary. Save a tree
